// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQyr0XLZApjDzwlK7KJBCZqz9kk4kKQMQ',
    appId: '1:504489315010:web:e19818dc9f899b4559095b',
    messagingSenderId: '504489315010',
    projectId: 'flavr-c527b',
    authDomain: 'flavr-c527b.firebaseapp.com',
    storageBucket: 'flavr-c527b.appspot.com',
    measurementId: 'G-2C4RTNEP50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADWA3r8MvQ4WhfZyCt0vpHF6q0yWwCFY',
    appId: '1:504489315010:android:74ba6e0c6a61db2e59095b',
    messagingSenderId: '504489315010',
    projectId: 'flavr-c527b',
    storageBucket: 'flavr-c527b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA27GiRGUFF4yNqejedOyI3zbpnhaPXJ0Q',
    appId: '1:504489315010:ios:73120fd1512868f659095b',
    messagingSenderId: '504489315010',
    projectId: 'flavr-c527b',
    storageBucket: 'flavr-c527b.appspot.com',
    androidClientId: '504489315010-h6rh9b3405iliftjmp3l5fu6ipt25ma4.apps.googleusercontent.com',
    iosClientId: '504489315010-t87tv0fkdof28tjsq6e5csgeesunh33i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgsrncoSXgLw0TycjhGO4zzhyl2Y2akKU',
    appId: '1:504489315010:ios:74e17afa68bd6ba559095b',
    messagingSenderId: '504489315010',
    projectId: 'flavr-c527b',
    storageBucket: 'flavr-c527b.appspot.com',
    androidClientId: '504489315010-h6rh9b3405iliftjmp3l5fu6ipt25ma4.apps.googleusercontent.com',
    iosClientId: '504489315010-2m51cb97ritbdne2pi8vlqtfbmp9hhv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavr.RunnerTests',
  );
}
