name: Build APK
env:
  FLUTTER_VERSION: "3.13.0"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: britannio/action-install-flutter@v1.1
        with:
          version: $FLUTTER_VERSION
      - name: Get Packages
        run: flutter pub get
      - name: build apk
        run: flutter build apk
      - name: Save the APK
        run: |
          RELEASE_ID=$(curl -X POST -H "Authorization: token $GH_TOKEN" -d '{"tag_name": "v1.0.0", "target_commitish": "main", "name": "Release v1.0.0", "body": "Release Notes"}' "https://api.github.com/repos/${{ github.repository }}/releases" | jq -r '.id')
          cd build/app/outputs/flutter-apk/
          curl -H "Authorization: token $GH_TOKEN" -H "Content-Type: application/apk" --data-binary @app-release.apk "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=app-release.apk"
